[project]
name = "founderscan"
version = "0.1.0"
description = "CLI tool for calculating co-founder stock and vesting schedules"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.0.0",
    "pydantic>=2.0.0",
    "rich>=13.0.0",
    "typer>=0.9.0",
]

